<?php
/**
 * @author  Lukáš
 * @version 1.0.0
 * @package Topazz
 */

namespace Topazz\Module;

use PHPUnit\Framework\TestCase;

class ModuleInstallerTest extends TestCase {

    /** @var ModuleInstaller $moduleInstaller */
    private $moduleInstaller;

    protected function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->moduleInstaller = new ModuleInstaller();
    }

    public function testListModules() {
        $modules = $this->moduleInstaller->listModules();
        var_dump($modules);
        $this->assertNotNull($modules);
    }
}
